version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: faildaily_frontend
    ports:
      - "80:80"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend-api
      dockerfile: ../docker/backend.Dockerfile
    container_name: faildaily_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../backend-api/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: faildaily_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
