version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    container_name: faildaily_traefik_local
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8000:80"      # Port 8000 pour éviter le conflit avec WAMP
      - "8080:8080"    # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    container_name: faildaily_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=50"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ../backend-api
      dockerfile: Dockerfile
    container_name: faildaily_backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api.entrypoints=web"
      - "traefik.http.routers.backend-api.priority=100"
      - "traefik.http.routers.backend-uploads.rule=Host(`localhost`) && PathPrefix(`/uploads`)"
      - "traefik.http.routers.backend-uploads.entrypoints=web"
      - "traefik.http.routers.backend-uploads.priority=90"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: faildaily_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
