version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: faildaily
      MYSQL_USER: faildaily_user
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ../..:/workspace
      - ../../backend-api/migrations/faildaily.sql:/docker-entrypoint-initdb.d/01_faildaily.sql:ro

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  backend:
    build:
      context: ../../backend-api
      dockerfile: ../docker/production/backend.prod.Dockerfile
    environment:
      NODE_ENV: test
      PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: faildaily
      DB_USER: faildaily_user
      DB_PASSWORD: root
      JWT_SECRET: e2e-secret
      APP_WEB_URL: http://frontend
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
      SMTP_USER: ''
      SMTP_PASS: ''
      SMTP_FROM: 'FailDaily <no-reply@faildaily.test>'
      CORS_ORIGIN: http://frontend
    depends_on:
      - db
      - mailhog
    ports:
      - "3001:3000"
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/production/frontend.prod.Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

  cypress:
    image: cypress/included:13.6.2
    working_dir: /e2e
    depends_on:
      - frontend
      - backend
    environment:
      CYPRESS_baseUrl: http://frontend
      CYPRESS_apiUrl: http://backend:3000/api
    volumes:
      - ../../e2e:/e2e
    command: ["cypress", "run", "--browser", "chrome"]

volumes:
  backend_uploads:
